name: 'marketo'
version: '1.0.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
on-run-start: "{{ lead_history_columns_warning() }}"

vars:
  marketo:
    lead_history_columns: ['lead_status', 'urgency', 'priority', 'relative_score', 'relative_urgency', 'demographic_score_marketing', 'behavior_score_marketing']
    activity_email_bounced: "{{ source('marketo', 'activity_email_bounced') }}"
    activity_click_email: "{{ source('marketo', 'activity_click_email') }}"
    activity_email_delivered: "{{ source('marketo', 'activity_email_delivered') }}"
    activity_open_email: "{{ source('marketo', 'activity_open_email') }}"
    activity_unsubscribe_email: "{{ source('marketo', 'activity_unsubscribe_email') }}"
    activity_send_email: "{{ source('marketo', 'activity_send_email') }}"
    activity_delete_lead: "{{ source('marketo', 'activity_delete_lead') }}"
    activity_merge_leads: "{{ source('marketo', 'activity_merge_leads') }}"
    change_data_value: "{{ source('marketo', 'activity_change_data_value') }}"
    lead: "{{ source('marketo', 'lead') }}"
    lead_describe: "{{ source('marketo', 'lead_describe') }}"
    campaigns: "{{ source('marketo', 'campaigns') }}"
    email_tempate_history: "{{ source('marketo', 'email_template_history') }}"
    program: "{{ source('marketo', 'program') }}"
    marketo__activity_send_email_passthrough_columns: []
    marketo__program_passthrough_columns: []

models:
  marketo:
    +materialized: table
    +schema: marketo
    intermediate:
      +materialized: ephemeral
    staging:
      +materialized: table
      +schema: marketo_source
      tmp:
        +materialized: view
