name: 'marketo_integration_tests'
version: '0.13.0'
profile: 'integration_tests'
config-version: 2

models:  
    +schema: "marketo_{{ var('directed_schema','dev') }}"  

vars:
    marketo_schema: marketo_integration_tests_8
    # marketo__enable_campaigns: false ## Uncomment for testing to disable campaigns
    # marketo__enable_programs: false ## Uncomment for testing to disable programs
    marketo_source:
        marketo_lead_identifier: "marketo_lead_data"
        marketo_lead_describe_identifier: "marketo_lead_describe_data"
        marketo_activity_change_data_value_identifier: "marketo_activity_change_data_value_data"
        marketo_campaign_identifier: "marketo_campaign_data"
        marketo_program_identifier: "marketo_program_data"
        marketo_email_template_history_identifier: "marketo_email_template_history_data"
        marketo_activity_click_email_identifier: "marketo_activity_click_email_data"
        marketo_activity_email_delivered_identifier: "marketo_activity_email_delivered_data"
        marketo_activity_email_bounced_identifier: "marketo_activity_email_bounced_data"
        marketo_activity_open_email_identifier: "marketo_activity_open_email_data"
        marketo_activity_unsubscribe_email_identifier: "marketo_activity_unsubscribe_email_data"
        marketo_activity_send_email_identifier: "marketo_activity_send_email_data"
        marketo_activity_delete_lead_identifier: "marketo_activity_delete_lead_data"
        marketo_activity_merge_leads_identifier: "marketo_activity_merge_leads_data"

dispatch:
    - macro_namespace: dbt_utils
      search_order: ['spark_utils', 'dbt_utils']

seeds:
    marketo_integration_tests:
        marketo_email_template_history_data:
            +column_types:
                created_at: timestamp
                updated_at: timestamp
        marketo_activity_change_data_value_data:
            +column_types:
                activity_date: timestamp  
        marketo_activity_send_email_data:
            +column_types:
                activity_date: timestamp  
        marketo_lead_data:
            +column_types:
                created_at: timestamp
